name: Carbonix Parameter Validation
on:
  push:
    branches:
      - CxPilot
      - master
    paths-ignore:
      # remove other vehicles
      - 'AntennaTracker/**'
      - 'ArduCopter/**'
      - 'ArduSub/**'
      - 'Blimp/**'
      - 'Rover/**'
      # remove non unrelated tools
      - 'Tools/AP_Bootloader/**'
      - 'Tools/bootloaders/**'
      - 'Tools/CHDK-Script/**'
      - 'Tools/CodeStyle/**'
      - 'Tools/completion/**'
      - 'Tools/CPUInfo/**'
      - 'Tools/debug/**'
      - 'Tools/environment_install/**'
      - 'Tools/FilterTestTool/**'
      - 'Tools/Frame_params/**'
      - 'Tools/geotag/**'
      - 'Tools/GIT_Test/**'
      - 'Tools/gittools/**'
      - 'Tools/Hello/**'
      - 'Tools/IO_Firmware/**'
      - 'Tools/Linux_HAL_Essentials/**'
      - 'Tools/LogAnalyzer/**'
      - 'Tools/Pozyx/**'
      - 'Tools/PrintVersion.py'
      - 'Tools/Replay/**'
      - 'Tools/ros2/**'
      - 'Tools/simulink/**'
      - 'Tools/UDP_Proxy/**'
      - 'Tools/vagrant/**'
      - 'Tools/Vicon/**'
      # Discard python file from Tools/scripts as not used
      - 'Tools/scripts/**.py'
      - 'Tools/scripts/build_sizes/**'
      - 'Tools/scripts/build_tests/**'
      - 'Tools/scripts/CAN/**'
      - 'Tools/scripts/signing/**'
      # Remove vehicles autotest
      - 'Tools/autotest/antennatracker.py'
      - 'Tools/autotest/arducopter.py'
      - 'Tools/autotest/arduplane.py'
      - 'Tools/autotest/ardusub.py'
      - 'Tools/autotest/balancebot.py'
      - 'Tools/autotest/helicopter.py'
      - 'Tools/autotest/location.txt'
      - 'Tools/autotest/rover.py'
      - 'Tools/autotest/sailboat.py'
      - 'Tools/autotest/swarminit.txt'
      # Remove markdown files as irrelevant
      - '**.md'
      # Remove dotfile at root directory
      - './.dir-locals.el'
      - './.dockerignore'
      - './.editorconfig'
      - './.flake8'
      - './.gitattributes'
      - './.github'
      - './.gitignore'
      - './.pre-commit-config.yaml'
      - './.pydevproject'
      - './.valgrind-suppressions'
      - './.valgrindrc'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
      # Remove some directories check
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      # Remove change on other workflows
      - '.github/workflows/test_environment.yml'
      - '.github/workflows/cache_cleanup.yml'
      - '.github/workflows/cygwin_build.yml'
      - '.github/workflows/test_ccache.yml'
      - '.github/workflows/test_linux_sbc.yml'
      - '.github/workflows/test_scripts.yml'
      - '.github/workflows/test_sitl_periph.yml'
      - '.github/workflows/test_sitl_sub.yml'
      - '.github/workflows/ccache.env'
      - '.github/workflows/esp32_build.yml'
      - '.github/workflows/test_chibios.yml'
      - '.github/workflows/test_replay.yml'
      - '.github/workflows/test_sitl_blimp.yml'
      - '.github/workflows/test_sitl_plane.yml'
      - '.github/workflows/test_sitl_tracker.yml'
      - '.github/workflows/colcon.yml'
      - '.github/workflows/test_dds.yml'
      - '.github/workflows/test_scripting.yml'
      - '.github/workflows/test_sitl_copter.yml'
      - '.github/workflows/test_sitl_rover.yml'
      - '.github/workflows/test_unit_tests.yml'

  pull_request:
    paths-ignore:
      # remove other vehicles
      - 'AntennaTracker/**'
      - 'ArduCopter/**'
      - 'ArduSub/**'
      - 'Blimp/**'
      - 'Rover/**'
      # remove non unrelated tools
      - 'Tools/AP_Bootloader/**'
      - 'Tools/bootloaders/**'
      - 'Tools/CHDK-Script/**'
      - 'Tools/CodeStyle/**'
      - 'Tools/completion/**'
      - 'Tools/CPUInfo/**'
      - 'Tools/debug/**'
      - 'Tools/environment_install/**'
      - 'Tools/FilterTestTool/**'
      - 'Tools/Frame_params/**'
      - 'Tools/geotag/**'
      - 'Tools/GIT_Test/**'
      - 'Tools/gittools/**'
      - 'Tools/Hello/**'
      - 'Tools/IO_Firmware/**'
      - 'Tools/Linux_HAL_Essentials/**'
      - 'Tools/LogAnalyzer/**'
      - 'Tools/Pozyx/**'
      - 'Tools/PrintVersion.py'
      - 'Tools/Replay/**'
      - 'Tools/ros2/**'
      - 'Tools/simulink/**'
      - 'Tools/UDP_Proxy/**'
      - 'Tools/vagrant/**'
      - 'Tools/Vicon/**'
      # Discard python file from Tools/scripts as not used
      - 'Tools/scripts/**.py'
      - 'Tools/scripts/build_sizes/**'
      - 'Tools/scripts/build_tests/**'
      - 'Tools/scripts/CAN/**'
      - 'Tools/scripts/signing/**'
      # Remove vehicles autotest
      - 'Tools/autotest/antennatracker.py'
      - 'Tools/autotest/arducopter.py'
      - 'Tools/autotest/arduplane.py'
      - 'Tools/autotest/ardusub.py'
      - 'Tools/autotest/balancebot.py'
      - 'Tools/autotest/helicopter.py'
      - 'Tools/autotest/location.txt'
      - 'Tools/autotest/rover.py'
      - 'Tools/autotest/sailboat.py'
      - 'Tools/autotest/swarminit.txt'
      # Remove markdown files as irrelevant
      - '**.md'
      # Remove dotfile at root directory
      - './.dir-locals.el'
      - './.dockerignore'
      - './.editorconfig'
      - './.flake8'
      - './.gitattributes'
      - './.github'
      - './.gitignore'
      - './.pre-commit-config.yaml'
      - './.pydevproject'
      - './.valgrind-suppressions'
      - './.valgrindrc'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
      # Remove some directories check
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      # Remove change on other workflows
      - '.github/workflows/test_environment.yml'
      - '.github/workflows/cache_cleanup.yml'
      - '.github/workflows/cygwin_build.yml'
      - '.github/workflows/test_ccache.yml'
      - '.github/workflows/test_linux_sbc.yml'
      - '.github/workflows/test_scripts.yml'
      - '.github/workflows/test_sitl_periph.yml'
      - '.github/workflows/test_sitl_sub.yml'
      - '.github/workflows/ccache.env'
      - '.github/workflows/esp32_build.yml'
      - '.github/workflows/test_chibios.yml'
      - '.github/workflows/test_replay.yml'
      - '.github/workflows/test_sitl_blimp.yml'
      - '.github/workflows/test_sitl_plane.yml'
      - '.github/workflows/test_sitl_tracker.yml'
      - '.github/workflows/colcon.yml'
      - '.github/workflows/test_dds.yml'
      - '.github/workflows/test_scripting.yml'
      - '.github/workflows/test_sitl_copter.yml'
      - '.github/workflows/test_sitl_rover.yml'
      - '.github/workflows/test_unit_tests.yml'

  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-parameters:
    runs-on: ubuntu-22.04  
    container: ardupilot/ardupilot-dev-base:v0.1.3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Param Check Unittests
        run: >
          python Tools/Carbonix_scripts/param_check_unittests.py

      - name: Check Periph Parameters
        run: >
          python Tools/Carbonix_scripts/param_check.py
          --vehicle=AP_Periph
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/cpn_params/**/*.par*m
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/payloads/**/cpn*.par*m
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/payloads/**/CPN*.par*m

      - name: Check Plane Parameters
        # Run even if the previous step fails
        if: success() || failure()
        run: >
          python Tools/Carbonix_scripts/param_check.py
          --vehicle=Plane
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/defaults.parm
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/payloads/**/Cube*.par*m
          libraries/AP_HAL_ChibiOS/hwdef/CarbonixCommon/payloads/**/cube*.par*m
          libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-Volanti/defaults.parm
          libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-Volanti/defaults.parm
          libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-Ottano/defaults.parm
          libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-Ottano/defaults.parm
